export const mockUsers = [
  {
    id: "u-admin",
    name: "Isaac Ramos",
    email: "lowmeetlowmeet@gmail.com",
    password: "admin",
    role: "ADMIN",
  },
  {
    id: "u-org-1",
    name: "Garage Norte",
    email: "org@lowmeet.com",
    password: "123456",
    role: "ORGANIZADOR",
  },
  {
    id: "u-visit-1",
    name: "Visitante Demo",
    email: "visitante@lowmeet.com",
    password: "123456",
    role: "VISITANTE",
  },
];

export const mockPendingApprovalEvents = [
  {
    id: "ev-3",
    name: "Expo Custom Sul",
    type: "Exposição",
    description: "Exposição de projetos custom e premiação por categoria.",
    datetime: "2026-04-25T14:30:00",
    city: "Curitiba",
    state: "PR",
    street: "Centro de Convencoes Barigui",
    number: "S/N",
    complement: "",
    location: "Centro de Convencoes Barigui",
    ticketType: "free",
    ticketPrice: null,
    image:
      "https://images.unsplash.com/photo-1514316454349-750a7fd3da3a?auto=format&fit=crop&w=1200&q=80",
    organizerId: "u-org-1",
    organizerName: "Garage Norte",
    tags: ["custom", "expo", "classic"],
    status: "pending",
    createdAt: "2026-03-28T17:00:00",
  },
  {
    id: "ev-4",
    name: "Noite Turbo Vale",
    type: "Encontro",
    description:
      "Encontro noturno com exposição de carros turbo, batalha de capôs e praça de food trucks.",
    datetime: "2026-05-02T20:30:00",
    city: "Sao Jose dos Campos",
    state: "SP",
    street: "Av. Jorge Zarur",
    number: "1520",
    complement: "Estacionamento G2",
    location: "Av. Jorge Zarur, 1520 - Estacionamento G2",
    ticketType: "paid",
    ticketPrice: 30,
    image:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    organizerId: "u-org-1",
    organizerName: "Garage Norte",
    tags: ["turbo", "night", "meet"],
    status: "pending",
    createdAt: "2026-03-30T18:10:00",
  },
  {
    id: "ev-5",
    name: "Feirao Classicos do Porto",
    type: "Exposição",
    description:
      "Evento diurno com feira de peças antigas, sessão de fotos e área exclusiva para clubes.",
    datetime: "2026-05-10T10:00:00",
    city: "Porto Alegre",
    state: "RS",
    street: "Av. Padre Cacique",
    number: "891",
    complement: "Pavilhao B",
    location: "Av. Padre Cacique, 891 - Pavilhao B",
    ticketType: "free",
    ticketPrice: null,
    image:
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80",
    organizerId: "u-org-1",
    organizerName: "Garage Norte",
    tags: ["classicos", "feira", "clubes"],
    status: "pending",
    createdAt: "2026-03-30T09:45:00",
  },
  {
    id: "ev-6",
    name: "Sunset Premium Wheels",
    type: "Exposição",
    description:
      "Mostra de rodas premium e projetos stance com votação popular e área instagramável.",
    datetime: "2026-05-18T17:30:00",
    city: "Florianopolis",
    state: "SC",
    street: "Av. Beira Mar Norte",
    number: "5000",
    complement: "Arena Open Mall",
    location: "Av. Beira Mar Norte, 5000 - Arena Open Mall",
    ticketType: "paid",
    ticketPrice: 55,
    image:
      "https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=1200&q=80",
    organizerId: "u-org-1",
    organizerName: "Garage Norte",
    tags: ["wheels", "stance", "sunset"],
    status: "pending",
    createdAt: "2026-03-30T21:20:00",
  },
];

export const mockEvents = [
  {
    id: "ev-1",
    name: "Encontro Noturno Stance SP",
    type: "Encontro",
    description: "Noite com carros stance, som automotivo e praça de alimentação.",
    datetime: "2026-04-12T20:00:00",
    city: "Sao Paulo",
    state: "SP",
    street: "Av. Dr. Gastao Vidigal",
    number: "1946",
    complement: "Vila Leopoldina",
    location: "Av. Dr. Gastao Vidigal, 1946 - Vila Leopoldina",
    ticketType: "free",
    ticketPrice: null,
    image:
      "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=1200&q=80",
    organizerId: "u-org-1",
    organizerName: "Garage Norte",
    tags: ["stance", "som", "night"],
    status: "approved",
    createdAt: "2026-03-20T10:00:00",
  },
  {
    id: "ev-2",
    name: "Track Day Interlagos Pro",
    type: "Track Day",
    description: "Baterias guiadas para iniciantes e avancados com cronometro.",
    datetime: "2026-04-18T09:00:00",
    city: "Sao Paulo",
    state: "SP",
    street: "Autodromo de Interlagos",
    number: "Portao 7",
    complement: "",
    location: "Autodromo de Interlagos - Portao 7",
    ticketType: "paid",
    ticketPrice: 85,
    image:
      "https://images.unsplash.com/photo-1471478331149-c72f17e33c73?auto=format&fit=crop&w=1200&q=80",
    organizerId: "u-admin",
    organizerName: "Isaac Ramos",
    tags: ["trackday", "turbo", "lap"],
    status: "approved",
    createdAt: "2026-03-23T14:00:00",
  },
  ...mockPendingApprovalEvents,
];

export const mockStressTestEvents = [
  {
    id: "ev-test-1",
    name: "Warm-up Stance Meetup",
    type: "Encontro",
    description: "Encontro de aquecimento com fotos, som e area gourmet.",
    datetime: "2026-04-12T09:00:00",
    city: "Sao Paulo",
    state: "SP",
    street: "Av. Santos Dumont",
    number: "1200",
    complement: "",
    location: "Av. Santos Dumont, 1200",
    ticketType: "free",
    ticketPrice: null,
    image:
      "https://images.unsplash.com/photo-1517524206127-48bbd363f3d7?auto=format&fit=crop&w=1200&q=80",
    organizerId: "u-org-1",
    organizerName: "Garage Norte",
    tags: ["stance", "meet", "street"],
    status: "approved",
    createdAt: "2026-03-26T10:00:00",
  },
  {
    id: "ev-test-2",
    name: "Drag Simulado Night",
    type: "Arrancada",
    description: "Sessao controlada com alinhamento e tomada de tempo.",
    datetime: "2026-04-12T11:00:00",
    city: "Sao Paulo",
    state: "SP",
    street: "Rua do Autodromo",
    number: "455",
    complement: "Lote 4",
    location: "Rua do Autodromo, 455 - Lote 4",
    ticketType: "paid",
    ticketPrice: 35,
    image:
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80",
    organizerId: "u-org-1",
    organizerName: "Garage Norte",
    tags: ["arrancada", "turbo"],
    status: "approved",
    createdAt: "2026-03-27T11:00:00",
  },
  {
    id: "ev-test-3",
    name: "Track Clinic Interlagos",
    type: "Track Day",
    description: "Clinica de pilotagem e voltas monitoradas.",
    datetime: "2026-04-12T14:00:00",
    city: "Sao Paulo",
    state: "SP",
    street: "Autodromo de Interlagos",
    number: "Portao 8",
    complement: "",
    location: "Autodromo de Interlagos - Portao 8",
    ticketType: "paid",
    ticketPrice: 120,
    image:
      "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80",
    organizerId: "u-admin",
    organizerName: "Isaac Ramos",
    tags: ["trackday", "clinic"],
    status: "approved",
    createdAt: "2026-03-28T09:00:00",
  },
  {
    id: "ev-test-4",
    name: "Sunset Car Audio",
    type: "Encontro",
    description: "Show de som e iluminacao com premiacoes rapidas.",
    datetime: "2026-04-12T16:30:00",
    city: "Sao Paulo",
    state: "SP",
    street: "Av. Cruzeiro do Sul",
    number: "2000",
    complement: "",
    location: "Av. Cruzeiro do Sul, 2000",
    ticketType: "free",
    ticketPrice: null,
    image:
      "https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=1200&q=80",
    organizerId: "u-org-1",
    organizerName: "Garage Norte",
    tags: ["som", "sunset"],
    status: "approved",
    createdAt: "2026-03-28T12:30:00",
  },
  {
    id: "ev-test-5",
    name: "Midnight Drift Session",
    type: "Encontro",
    description: "Sessao noturna com exibicao e area para publico.",
    datetime: "2026-04-12T22:00:00",
    city: "Sao Paulo",
    state: "SP",
    street: "Rua das Oficinas",
    number: "77",
    complement: "",
    location: "Rua das Oficinas, 77",
    ticketType: "paid",
    ticketPrice: 45,
    image:
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80",
    organizerId: "u-org-1",
    organizerName: "Garage Norte",
    tags: ["drift", "night"],
    status: "approved",
    createdAt: "2026-03-29T08:00:00",
  },
];

export const mockBanners = [
  {
    id: "bn-1",
    brandName: "TurboMax Performance",
    type: "oficina",
    image:
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",
    link: "https://instagram.com",
    position: "home-top",
    active: true,
    story:
      "A TurboMax nasceu da paixão por preparação turbo e acerto fino para projetos de rua e pista. Hoje é referência em performance confiável.",
  },
  {
    id: "bn-2",
    brandName: "DT Garage Store",
    type: "loja",
    image:
      "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=80",
    link: "https://wa.me/5511999999999",
    position: "home-middle",
    active: true,
    story:
      "A DT Garage Store começou como uma pequena loja de acessórios e virou ponto de encontro de quem busca peças, estilo e suporte para projetos custom.",
  },
  {
    id: "bn-3",
    brandName: "Garage Performance",
    type: "patrocinador",
    image:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    link: "https://example.com",
    position: "home-bottom",
    active: true,
    story:
      "A Garage Performance atua no ecossistema automotivo apoiando eventos e iniciativas da comunidade, conectando marcas e apaixonados por carros.",
  },
  {
    id: "bn-4",
    brandName: "Octane Motors",
    type: "oficina",
    image:
      "https://images.unsplash.com/photo-1533106418989-88406c7cc8ca?auto=format&fit=crop&w=1200&q=80",
    link: "https://instagram.com",
    position: "events-top",
    active: true,
    story:
      "A Octane Motors é focada em manutenção especializada e upgrades para veículos esportivos, com histórico forte em track days e encontros técnicos.",
  },
  {
    id: "bn-5",
    brandName: "Street Customs",
    type: "loja",
    image:
      "https://images.unsplash.com/photo-1517142089942-ba376ce32a2e?auto=format&fit=crop&w=1200&q=80",
    link: "https://example.com",
    position: "events-bottom",
    active: true,
    story:
      "A Street Customs construiu sua história transformando carros comuns em projetos únicos, valorizando acabamento premium e identidade visual.",
  },
  {
    id: "bn-6",
    brandName: "Nitro Wheels Club",
    type: "patrocinador",
    image:
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=1200&q=80",
    link: "https://instagram.com",
    position: "events-after-calendar",
    active: true,
    story:
      "A Nitro Wheels Club promove ativações com marcas e encontros temáticos, trazendo experiências para o público logo após o calendário de eventos.",
  },
];
